#!/bin/bash
echo "Enter the year"
read a
if (( ( a % 400 == 0 ) || ( a % 4 == 0 && a % 100 != 0 ) ))
        then
                echo "Leap year"
        else
                echo "Not leap year"
fi
